### ISSUE TITLE
docs/Config_Reference.md is missing(?)

### ISSUE THREAD

**Issue by YesterdaysCoffee** [joseph-greiner/tridex_mods#2]
the file docs/Config_Reference.md is missing, it was referenced in IDEX_mode.cfg

I'm working on getting your IDEX macros to work with my TrideX-17.

thanks,
Mac McCaskie

**Comment by joseph-greiner** [comment]
added a config_reference.md in the printer_configuration folder, updated IDEX_mode.cfg to reflect this
